### ISSUE TITLE
Hardcoded Google Cloud Project ids

### ISSUE THREAD

**Issue by ghost** [hashicorp/rtmo-consul#1]
All the packer json files contain:   "project_id": "rtmo-consul" .  
As a result of that builds in Atlas ends with error: 
"==> googlecompute: Error creating instance: googleapi: Error 404: The resource 'projects/rtmo-consul' was not found, notFound
Build 'googlecompute' errored: Error creating instance: googleapi: Error 404: The resource 'projects/rtmo-consul'

Project id should be a variable, and one of the steps of https://atlas.hashicorp.com/tutorial/automated-service-discovery tutorial should be about setting this variable to a Google Cloud project id that a user has a write access to.

**Comment by ghost** [comment]
https://github.com/hashicorp/atlas-examples/blob/master/google-hyperspace/packer/hyperspace-fe.json is an example of how to do than in a right way

**Comment by mootpt** [comment]
@Dnefedkin it seems this just needs to be modified in the instructions (ie create a project with the name rtmo-consul).

**Comment by ghost** [comment]
Project Ids in Google Cloud Platform are globally unique, so it's impossible for everyone to create a project with id rtmo-consul

**Comment by mootpt** [comment]
thanks for catching this. Though not sure https://github.com/hashicorp/atlas-examples/blob/master/google-hyperspace/packer/hyperspace-fe.json#L3 will prevent projectid collisions. I am thinking I may go with something like rtmo-consul-{{user `atlas_username`}} as it's already set and something I can autofill pretty painlessly in the tutorial.

**Comment by mootpt** [comment]
Fixed. Thanks again: https://github.com/hashicorp/rtmo-consul/commit/34a4398b3d058d272d7e055e7fb2c6d919b51162
